name: Deploy db for DEV environment

on:
  push:
    branches: "AnuragGoel04-patch-1"
  workflow_dispatch:

jobs:
  deploy-db-to-dev:
    uses: ./.github/workflows/DB/db.yml
    with:
      env: 'dev'
    secrets: inherit
