name: Deploy TF on Sandbox

on:
  push:
    branches: ["AnuragGoel04-patch-1"]
  workflow_dispatch:

jobs:
  deploy-to-sandbox:
    uses: ./.github/workflows/terraform.yml
    with:
      env-no-approvers: 'sandbox'
      env-with-approvers: 'sandbox'
      apply-tf-changes: true
      delta-env: 'sbx'
    secrets: inherit
