name: Deploy TF on UAT

on:
  push:
    branches: ["AnuragGoel04-patch-1"]
  workflow_dispatch:

jobs:
  deploy-db-to-prod:
    uses: ./.github/workflows/terraform.yml
    with:
      env-no-approvers: 'sandbox'
      env-with-approvers: 'sandbox'
      apply-tf-changes: 'true'
    secrets: inherit
