name: Deploy TF on Sandbox

on:
  push:
    branches: ["AnuragGoel04-patch-1"]
    paths:
      - 'shared-infra/database/**'
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: Release tag name
        required: true

jobs:
  deploy-to-sandbox:
    uses: ./.github/workflows/terraform.yml
    with:
      github-env: 'sandbox'
      apply-tf-changes: true
      delta-env: 'sbx'
      release-tag: "${{ github.event.inputs.release_tag }}"
    secrets: inherit
