name: Deploy TF on UAT

on:
  push:
    tags: ['*']
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-db-to-uat:
    uses: ./.github/workflows/terraform.yml
    with:
      github-env: 'uat'
      delta-env: 'uat'
      apply-tf-changes: 'true'
    secrets: inherit
