name: Deploy TF on Prod

on:
  workflow_dispatch:

jobs:
  deploy-db-to-prod:
    uses: ./.github/workflows/terraform.yml
    with:
      env-no-approval: 'prod-no-approvers'
      env-with-approval: 'prod'
      apply-tf-changes: 'true'
    secrets: inherit
