name: Deploy TF on Prod

on:
  workflow_dispatch:

jobs:
  deploy-db-to-prod:
    uses: ./.github/workflows/terraform.yml
    with:
      github-env: 'uat'
      delta-env: 'uat'
      release-tag: 'test'
      apply-tf-changes: true
    secrets: inherit
