name: Deploy TF on DEV

on:
  push:
    branches: "AnuragGoel04-patch-1"
  workflow_dispatch:

jobs:
  deploy-db-to-dev:
    uses: ./.github/workflows/terraform2.yml
    with:
      env: 'dev'
    secrets: inherit
