name: Pull request verification plan

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  verify-infra-changes:
    uses: ./.github/workflows/terraform.yml
    with:
      env-no-approvers: 'uat-no-approvers'
      env-with-approvers: 'uat'
    secrets: inherit
