name: Pull request verification plan

on:
  pull_request:
    branches: [main,AnuragGoel04-patch-1]

jobs:
  verify-infra-changes:
    uses: ./.github/workflows/terraform2.yml
    with:
      env: 'prod'
    secrets: inherit
