name: Pull request verification plan

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  verify-db-changes:
    uses: ./.github/workflows/terraform.yml
    with:
      github-env: 'uat'
      delta-env: 'uat'
    secrets: inherit
    
  verify-ui-changes:
    uses: ./.github/workflows/test-checkout.yml
    with:
      github-env: 'uat'
      delta-env: 'uat'
      release-tag: 'main'
    secrets: inherit
