name: Pull request verification plan

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  verify-infra-changes:
    uses: ./.github/workflows/terraform.yml
    with:
      github-env: 'uat'
      delta-env: 'uat'
    secrets: inherit
