name: Pull request verification plan

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  verify-infra-changes:
    uses: ./.github/workflows/terraform2.yml
    with:
      env-plan-no-approval: 'uat-no-approvers'
      env-apply-with-approval: 'uat'
    secrets: inherit
