name: 'Test Checkout'

on:
  workflow_call:
    inputs:
      release-tag:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      release-tag:
        required: false
        default: ''
        type: string

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the tag
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: "${{  inputs.release-tag  }}"
